name = "topolo-feed-api"
main = "src/index.ts"
compatibility_date = "2025-01-05"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "TOPOLO_FEED_CONFIG"
id = "6a325c245ac0433696b3a127a8da3ee8"

[[kv_namespaces]]
binding = "TOPOLO_STATE"
id = "37a037b342994ab5b722b12746d7cbd7"
